// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'api/types.dart';
import 'api/vault.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_IronVaultDbPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDbPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  IronVaultDb
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    dynamic raw,
  );

  @protected
  IronVaultDb
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    dynamic raw,
  );

  @protected
  IronVaultDb
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    dynamic raw,
  );

  @protected
  Map<String, SqlValue> dco_decode_Map_String_sql_value_None(dynamic raw);

  @protected
  IronVaultDb
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AggExpr dco_decode_agg_expr(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  QuerySpec dco_decode_box_autoadd_query_spec(dynamic raw);

  @protected
  SqlValue dco_decode_box_autoadd_sql_value(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  VaultConfig dco_decode_box_autoadd_vault_config(dynamic raw);

  @protected
  CheckpointMode dco_decode_checkpoint_mode(dynamic raw);

  @protected
  CheckpointResult dco_decode_checkpoint_result(dynamic raw);

  @protected
  Condition dco_decode_condition(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IntegrityReport dco_decode_integrity_report(dynamic raw);

  @protected
  JoinSpec dco_decode_join_spec(dynamic raw);

  @protected
  List<Map<String, SqlValue>> dco_decode_list_Map_String_sql_value_None(
    dynamic raw,
  );

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AggExpr> dco_decode_list_agg_expr(dynamic raw);

  @protected
  List<Condition> dco_decode_list_condition(dynamic raw);

  @protected
  List<JoinSpec> dco_decode_list_join_spec(dynamic raw);

  @protected
  List<List<Condition>> dco_decode_list_list_condition(dynamic raw);

  @protected
  List<OrderBy> dco_decode_list_order_by(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, SqlValue)> dco_decode_list_record_string_sql_value(dynamic raw);

  @protected
  List<SqlValue> dco_decode_list_sql_value(dynamic raw);

  @protected
  List<UpdateEntry> dco_decode_list_update_entry(dynamic raw);

  @protected
  Map<String, SqlValue>? dco_decode_opt_Map_String_sql_value_None(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  OrderBy dco_decode_order_by(dynamic raw);

  @protected
  Page dco_decode_page(dynamic raw);

  @protected
  QuerySpec dco_decode_query_spec(dynamic raw);

  @protected
  (String, SqlValue) dco_decode_record_string_sql_value(dynamic raw);

  @protected
  SqlValue dco_decode_sql_value(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpdateEntry dco_decode_update_entry(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VaultConfig dco_decode_vault_config(dynamic raw);

  @protected
  VaultStats dco_decode_vault_stats(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  IronVaultDb
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    SseDeserializer deserializer,
  );

  @protected
  IronVaultDb
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    SseDeserializer deserializer,
  );

  @protected
  IronVaultDb
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, SqlValue> sse_decode_Map_String_sql_value_None(
    SseDeserializer deserializer,
  );

  @protected
  IronVaultDb
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AggExpr sse_decode_agg_expr(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  QuerySpec sse_decode_box_autoadd_query_spec(SseDeserializer deserializer);

  @protected
  SqlValue sse_decode_box_autoadd_sql_value(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  VaultConfig sse_decode_box_autoadd_vault_config(SseDeserializer deserializer);

  @protected
  CheckpointMode sse_decode_checkpoint_mode(SseDeserializer deserializer);

  @protected
  CheckpointResult sse_decode_checkpoint_result(SseDeserializer deserializer);

  @protected
  Condition sse_decode_condition(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IntegrityReport sse_decode_integrity_report(SseDeserializer deserializer);

  @protected
  JoinSpec sse_decode_join_spec(SseDeserializer deserializer);

  @protected
  List<Map<String, SqlValue>> sse_decode_list_Map_String_sql_value_None(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AggExpr> sse_decode_list_agg_expr(SseDeserializer deserializer);

  @protected
  List<Condition> sse_decode_list_condition(SseDeserializer deserializer);

  @protected
  List<JoinSpec> sse_decode_list_join_spec(SseDeserializer deserializer);

  @protected
  List<List<Condition>> sse_decode_list_list_condition(
    SseDeserializer deserializer,
  );

  @protected
  List<OrderBy> sse_decode_list_order_by(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, SqlValue)> sse_decode_list_record_string_sql_value(
    SseDeserializer deserializer,
  );

  @protected
  List<SqlValue> sse_decode_list_sql_value(SseDeserializer deserializer);

  @protected
  List<UpdateEntry> sse_decode_list_update_entry(SseDeserializer deserializer);

  @protected
  Map<String, SqlValue>? sse_decode_opt_Map_String_sql_value_None(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  OrderBy sse_decode_order_by(SseDeserializer deserializer);

  @protected
  Page sse_decode_page(SseDeserializer deserializer);

  @protected
  QuerySpec sse_decode_query_spec(SseDeserializer deserializer);

  @protected
  (String, SqlValue) sse_decode_record_string_sql_value(
    SseDeserializer deserializer,
  );

  @protected
  SqlValue sse_decode_sql_value(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpdateEntry sse_decode_update_entry(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VaultConfig sse_decode_vault_config(SseDeserializer deserializer);

  @protected
  VaultStats sse_decode_vault_stats(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    IronVaultDb self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    IronVaultDb self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    IronVaultDb self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_sql_value_None(
    Map<String, SqlValue> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    IronVaultDb self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_agg_expr(AggExpr self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_query_spec(
    QuerySpec self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sql_value(
    SqlValue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_vault_config(
    VaultConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_checkpoint_mode(
    CheckpointMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_checkpoint_result(
    CheckpointResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_condition(Condition self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_integrity_report(
    IntegrityReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_join_spec(JoinSpec self, SseSerializer serializer);

  @protected
  void sse_encode_list_Map_String_sql_value_None(
    List<Map<String, SqlValue>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_agg_expr(List<AggExpr> self, SseSerializer serializer);

  @protected
  void sse_encode_list_condition(
    List<Condition> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_join_spec(List<JoinSpec> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_condition(
    List<List<Condition>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_order_by(List<OrderBy> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_sql_value(
    List<(String, SqlValue)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sql_value(List<SqlValue> self, SseSerializer serializer);

  @protected
  void sse_encode_list_update_entry(
    List<UpdateEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_Map_String_sql_value_None(
    Map<String, SqlValue>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_order_by(OrderBy self, SseSerializer serializer);

  @protected
  void sse_encode_page(Page self, SseSerializer serializer);

  @protected
  void sse_encode_query_spec(QuerySpec self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_sql_value(
    (String, SqlValue) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sql_value(SqlValue self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_update_entry(UpdateEntry self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_vault_config(VaultConfig self, SseSerializer serializer);

  @protected
  void sse_encode_vault_stats(VaultStats self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDbPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_iron_vault_pkg_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDbPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDbPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_iron_vault_pkg_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDbPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
