// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/crypto.dart';
import 'api/simple.dart';
import 'api/types.dart';
import 'api/vault.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_IronVaultDbPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  IronVaultDb
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    dynamic raw,
  );

  @protected
  IronVaultDb
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    dynamic raw,
  );

  @protected
  IronVaultDb
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    dynamic raw,
  );

  @protected
  Map<String, SqlValue> dco_decode_Map_String_sql_value_None(dynamic raw);

  @protected
  IronVaultDb
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    dynamic raw,
  );

  @protected
  RustStreamSink<Map<String, SqlValue>>
  dco_decode_StreamSink_Map_String_sql_value_None_Sse(dynamic raw);

  @protected
  RustStreamSink<List<Map<String, SqlValue>>>
  dco_decode_StreamSink_list_Map_String_sql_value_None_Sse(dynamic raw);

  @protected
  RustStreamSink<Map<String, SqlValue>?>
  dco_decode_StreamSink_opt_Map_String_sql_value_None_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AggExpr dco_decode_agg_expr(dynamic raw);

  @protected
  AuditEntry dco_decode_audit_entry(dynamic raw);

  @protected
  AuditIntegrityReport dco_decode_audit_integrity_report(dynamic raw);

  @protected
  BackupResult dco_decode_backup_result(dynamic raw);

  @protected
  BackupVerifyReport dco_decode_backup_verify_report(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  QuerySpec dco_decode_box_autoadd_query_spec(dynamic raw);

  @protected
  SqlValue dco_decode_box_autoadd_sql_value(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  VaultConfig dco_decode_box_autoadd_vault_config(dynamic raw);

  @protected
  CheckpointMode dco_decode_checkpoint_mode(dynamic raw);

  @protected
  CheckpointResult dco_decode_checkpoint_result(dynamic raw);

  @protected
  Condition dco_decode_condition(dynamic raw);

  @protected
  ExportFormat dco_decode_export_format(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IntegrityReport dco_decode_integrity_report(dynamic raw);

  @protected
  JoinSpec dco_decode_join_spec(dynamic raw);

  @protected
  List<Map<String, SqlValue>> dco_decode_list_Map_String_sql_value_None(
    dynamic raw,
  );

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AggExpr> dco_decode_list_agg_expr(dynamic raw);

  @protected
  List<AuditEntry> dco_decode_list_audit_entry(dynamic raw);

  @protected
  List<Condition> dco_decode_list_condition(dynamic raw);

  @protected
  List<JoinSpec> dco_decode_list_join_spec(dynamic raw);

  @protected
  List<List<Condition>> dco_decode_list_list_condition(dynamic raw);

  @protected
  List<MigrationRecord> dco_decode_list_migration_record(dynamic raw);

  @protected
  List<Op> dco_decode_list_op(dynamic raw);

  @protected
  List<OrderBy> dco_decode_list_order_by(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, SqlValue)> dco_decode_list_record_string_sql_value(dynamic raw);

  @protected
  List<SqlValue> dco_decode_list_sql_value(dynamic raw);

  @protected
  List<UpdateEntry> dco_decode_list_update_entry(dynamic raw);

  @protected
  List<VaultMigration> dco_decode_list_vault_migration(dynamic raw);

  @protected
  MigrationRecord dco_decode_migration_record(dynamic raw);

  @protected
  MigrationReport dco_decode_migration_report(dynamic raw);

  @protected
  Op dco_decode_op(dynamic raw);

  @protected
  Map<String, SqlValue>? dco_decode_opt_Map_String_sql_value_None(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  OrderBy dco_decode_order_by(dynamic raw);

  @protected
  Page dco_decode_page(dynamic raw);

  @protected
  QuerySpec dco_decode_query_spec(dynamic raw);

  @protected
  (String, SqlValue) dco_decode_record_string_sql_value(dynamic raw);

  @protected
  RestoreResult dco_decode_restore_result(dynamic raw);

  @protected
  SqlValue dco_decode_sql_value(dynamic raw);

  @protected
  TransactionResult dco_decode_transaction_result(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UpdateEntry dco_decode_update_entry(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VaultConfig dco_decode_vault_config(dynamic raw);

  @protected
  VaultMigration dco_decode_vault_migration(dynamic raw);

  @protected
  VaultStats dco_decode_vault_stats(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  IronVaultDb
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    SseDeserializer deserializer,
  );

  @protected
  IronVaultDb
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    SseDeserializer deserializer,
  );

  @protected
  IronVaultDb
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, SqlValue> sse_decode_Map_String_sql_value_None(
    SseDeserializer deserializer,
  );

  @protected
  IronVaultDb
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<Map<String, SqlValue>>
  sse_decode_StreamSink_Map_String_sql_value_None_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<Map<String, SqlValue>>>
  sse_decode_StreamSink_list_Map_String_sql_value_None_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<Map<String, SqlValue>?>
  sse_decode_StreamSink_opt_Map_String_sql_value_None_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AggExpr sse_decode_agg_expr(SseDeserializer deserializer);

  @protected
  AuditEntry sse_decode_audit_entry(SseDeserializer deserializer);

  @protected
  AuditIntegrityReport sse_decode_audit_integrity_report(
    SseDeserializer deserializer,
  );

  @protected
  BackupResult sse_decode_backup_result(SseDeserializer deserializer);

  @protected
  BackupVerifyReport sse_decode_backup_verify_report(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  QuerySpec sse_decode_box_autoadd_query_spec(SseDeserializer deserializer);

  @protected
  SqlValue sse_decode_box_autoadd_sql_value(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  VaultConfig sse_decode_box_autoadd_vault_config(SseDeserializer deserializer);

  @protected
  CheckpointMode sse_decode_checkpoint_mode(SseDeserializer deserializer);

  @protected
  CheckpointResult sse_decode_checkpoint_result(SseDeserializer deserializer);

  @protected
  Condition sse_decode_condition(SseDeserializer deserializer);

  @protected
  ExportFormat sse_decode_export_format(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IntegrityReport sse_decode_integrity_report(SseDeserializer deserializer);

  @protected
  JoinSpec sse_decode_join_spec(SseDeserializer deserializer);

  @protected
  List<Map<String, SqlValue>> sse_decode_list_Map_String_sql_value_None(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AggExpr> sse_decode_list_agg_expr(SseDeserializer deserializer);

  @protected
  List<AuditEntry> sse_decode_list_audit_entry(SseDeserializer deserializer);

  @protected
  List<Condition> sse_decode_list_condition(SseDeserializer deserializer);

  @protected
  List<JoinSpec> sse_decode_list_join_spec(SseDeserializer deserializer);

  @protected
  List<List<Condition>> sse_decode_list_list_condition(
    SseDeserializer deserializer,
  );

  @protected
  List<MigrationRecord> sse_decode_list_migration_record(
    SseDeserializer deserializer,
  );

  @protected
  List<Op> sse_decode_list_op(SseDeserializer deserializer);

  @protected
  List<OrderBy> sse_decode_list_order_by(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, SqlValue)> sse_decode_list_record_string_sql_value(
    SseDeserializer deserializer,
  );

  @protected
  List<SqlValue> sse_decode_list_sql_value(SseDeserializer deserializer);

  @protected
  List<UpdateEntry> sse_decode_list_update_entry(SseDeserializer deserializer);

  @protected
  List<VaultMigration> sse_decode_list_vault_migration(
    SseDeserializer deserializer,
  );

  @protected
  MigrationRecord sse_decode_migration_record(SseDeserializer deserializer);

  @protected
  MigrationReport sse_decode_migration_report(SseDeserializer deserializer);

  @protected
  Op sse_decode_op(SseDeserializer deserializer);

  @protected
  Map<String, SqlValue>? sse_decode_opt_Map_String_sql_value_None(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  OrderBy sse_decode_order_by(SseDeserializer deserializer);

  @protected
  Page sse_decode_page(SseDeserializer deserializer);

  @protected
  QuerySpec sse_decode_query_spec(SseDeserializer deserializer);

  @protected
  (String, SqlValue) sse_decode_record_string_sql_value(
    SseDeserializer deserializer,
  );

  @protected
  RestoreResult sse_decode_restore_result(SseDeserializer deserializer);

  @protected
  SqlValue sse_decode_sql_value(SseDeserializer deserializer);

  @protected
  TransactionResult sse_decode_transaction_result(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UpdateEntry sse_decode_update_entry(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VaultConfig sse_decode_vault_config(SseDeserializer deserializer);

  @protected
  VaultMigration sse_decode_vault_migration(SseDeserializer deserializer);

  @protected
  VaultStats sse_decode_vault_stats(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    IronVaultDb self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    IronVaultDb self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    IronVaultDb self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_sql_value_None(
    Map<String, SqlValue> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    IronVaultDb self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_Map_String_sql_value_None_Sse(
    RustStreamSink<Map<String, SqlValue>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_Map_String_sql_value_None_Sse(
    RustStreamSink<List<Map<String, SqlValue>>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_opt_Map_String_sql_value_None_Sse(
    RustStreamSink<Map<String, SqlValue>?> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_agg_expr(AggExpr self, SseSerializer serializer);

  @protected
  void sse_encode_audit_entry(AuditEntry self, SseSerializer serializer);

  @protected
  void sse_encode_audit_integrity_report(
    AuditIntegrityReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_backup_result(BackupResult self, SseSerializer serializer);

  @protected
  void sse_encode_backup_verify_report(
    BackupVerifyReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_query_spec(
    QuerySpec self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sql_value(
    SqlValue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_vault_config(
    VaultConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_checkpoint_mode(
    CheckpointMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_checkpoint_result(
    CheckpointResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_condition(Condition self, SseSerializer serializer);

  @protected
  void sse_encode_export_format(ExportFormat self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_integrity_report(
    IntegrityReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_join_spec(JoinSpec self, SseSerializer serializer);

  @protected
  void sse_encode_list_Map_String_sql_value_None(
    List<Map<String, SqlValue>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_agg_expr(List<AggExpr> self, SseSerializer serializer);

  @protected
  void sse_encode_list_audit_entry(
    List<AuditEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_condition(
    List<Condition> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_join_spec(List<JoinSpec> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_condition(
    List<List<Condition>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_migration_record(
    List<MigrationRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_op(List<Op> self, SseSerializer serializer);

  @protected
  void sse_encode_list_order_by(List<OrderBy> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_sql_value(
    List<(String, SqlValue)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sql_value(List<SqlValue> self, SseSerializer serializer);

  @protected
  void sse_encode_list_update_entry(
    List<UpdateEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_vault_migration(
    List<VaultMigration> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_migration_record(
    MigrationRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_migration_report(
    MigrationReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_op(Op self, SseSerializer serializer);

  @protected
  void sse_encode_opt_Map_String_sql_value_None(
    Map<String, SqlValue>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_order_by(OrderBy self, SseSerializer serializer);

  @protected
  void sse_encode_page(Page self, SseSerializer serializer);

  @protected
  void sse_encode_query_spec(QuerySpec self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_sql_value(
    (String, SqlValue) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_restore_result(RestoreResult self, SseSerializer serializer);

  @protected
  void sse_encode_sql_value(SqlValue self, SseSerializer serializer);

  @protected
  void sse_encode_transaction_result(
    TransactionResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_update_entry(UpdateEntry self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_vault_config(VaultConfig self, SseSerializer serializer);

  @protected
  void sse_encode_vault_migration(
    VaultMigration self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_vault_stats(VaultStats self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIronVaultDb(
    int ptr,
  );
}
