// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Derive a 32-byte encryption key from a password and salt using Argon2id.
///
/// This is CPU-intensive by design — call from a background isolate in Dart.
///
/// Recommended production parameters:
/// - `memory_kb`: 65536 (64MB)
/// - `iterations`: 3
/// - `parallelism`: 4
///
/// The salt must be at least 16 bytes (32 recommended). Generate with `generate_salt()`.
Future<Uint8List> deriveKey({
  required String password,
  required List<int> salt,
  required int memoryKb,
  required int iterations,
  required int parallelism,
}) => RustLib.instance.api.crateApiCryptoDeriveKey(
  password: password,
  salt: salt,
  memoryKb: memoryKb,
  iterations: iterations,
  parallelism: parallelism,
);

/// Generate 32 cryptographically secure random bytes.
///
/// Use for encryption salt (store in platform secure storage)
/// or as a random key.
Uint8List generateSalt() => RustLib.instance.api.crateApiCryptoGenerateSalt();

/// Encrypt a plaintext string using AES-256-GCM with a provided key.
///
/// Standalone version — does not require an open database.
/// Key must be exactly 32 bytes. Each call produces different ciphertext.
/// Returns JSON: `{"ct":"<base64>","nonce":"<base64>","kid":"v1"}`.
Future<String> encryptFieldStatic({
  required String plaintext,
  required List<int> key,
}) => RustLib.instance.api.crateApiCryptoEncryptFieldStatic(
  plaintext: plaintext,
  key: key,
);

/// Decrypt a ciphertext JSON string using AES-256-GCM with a provided key.
///
/// Standalone version — does not require an open database.
/// Key must be exactly 32 bytes.
Future<String> decryptFieldStatic({
  required String ciphertextJson,
  required List<int> key,
}) => RustLib.instance.api.crateApiCryptoDecryptFieldStatic(
  ciphertextJson: ciphertextJson,
  key: key,
);
