// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

@freezed
sealed class AggExpr with _$AggExpr {
  const AggExpr._();

  /// `COUNT(column) AS alias`
  const factory AggExpr.count({required String column, required String alias}) =
      AggExpr_Count;

  /// `SUM(column) AS alias`
  const factory AggExpr.sum({required String column, required String alias}) =
      AggExpr_Sum;

  /// `AVG(column) AS alias`
  const factory AggExpr.avg({required String column, required String alias}) =
      AggExpr_Avg;

  /// `MIN(column) AS alias`
  const factory AggExpr.min({required String column, required String alias}) =
      AggExpr_Min;

  /// `MAX(column) AS alias`
  const factory AggExpr.max({required String column, required String alias}) =
      AggExpr_Max;
}

/// WAL checkpoint mode.
enum CheckpointMode {
  /// Checkpoint as many WAL pages as possible without waiting.
  passive,

  /// Checkpoint all WAL pages, waiting for readers to finish.
  full,

  /// Like Full, then restart the WAL file from the beginning.
  restart,

  /// Like Restart, then truncate the WAL file to zero bytes.
  truncate,
}

/// Result of a WAL checkpoint operation.
class CheckpointResult {
  /// Total number of WAL pages.
  final int walPages;

  /// Number of pages successfully checkpointed.
  final int checkpointedPages;

  const CheckpointResult({
    required this.walPages,
    required this.checkpointedPages,
  });

  @override
  int get hashCode => walPages.hashCode ^ checkpointedPages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CheckpointResult &&
          runtimeType == other.runtimeType &&
          walPages == other.walPages &&
          checkpointedPages == other.checkpointedPages;
}

@freezed
sealed class Condition with _$Condition {
  const Condition._();

  /// `column = value`
  const factory Condition.eq({
    required String column,
    required SqlValue value,
  }) = Condition_Eq;

  /// `column != value`
  const factory Condition.notEq({
    required String column,
    required SqlValue value,
  }) = Condition_NotEq;

  /// `column > value`
  const factory Condition.gt({
    required String column,
    required SqlValue value,
  }) = Condition_Gt;

  /// `column >= value`
  const factory Condition.gte({
    required String column,
    required SqlValue value,
  }) = Condition_Gte;

  /// `column < value`
  const factory Condition.lt({
    required String column,
    required SqlValue value,
  }) = Condition_Lt;

  /// `column <= value`
  const factory Condition.lte({
    required String column,
    required SqlValue value,
  }) = Condition_Lte;

  /// `column LIKE pattern` (use % and _ wildcards)
  const factory Condition.like({
    required String column,
    required String pattern,
  }) = Condition_Like;

  /// `column BETWEEN low AND high`
  const factory Condition.between({
    required String column,
    required SqlValue low,
    required SqlValue high,
  }) = Condition_Between;

  /// `column IN (v1, v2, ...)`
  const factory Condition.in_({
    required String column,
    required List<SqlValue> values,
  }) = Condition_In;

  /// `column NOT IN (v1, v2, ...)`
  const factory Condition.notIn({
    required String column,
    required List<SqlValue> values,
  }) = Condition_NotIn;

  /// `column IS NULL`
  const factory Condition.isNull({required String column}) = Condition_IsNull;

  /// `column IS NOT NULL`
  const factory Condition.isNotNull({required String column}) =
      Condition_IsNotNull;

  /// Raw SQL fragment with parameterized values.
  /// The SQL is inserted as-is — caller is responsible for safety.
  const factory Condition.raw({
    required String sql,
    required List<SqlValue> params,
  }) = Condition_Raw;
}

/// Result of a database integrity check.
class IntegrityReport {
  /// True if no corruption detected.
  final bool isClean;

  /// List of error messages (empty if clean).
  final List<String> errors;

  const IntegrityReport({required this.isClean, required this.errors});

  @override
  int get hashCode => isClean.hashCode ^ errors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IntegrityReport &&
          runtimeType == other.runtimeType &&
          isClean == other.isClean &&
          errors == other.errors;
}

@freezed
sealed class JoinSpec with _$JoinSpec {
  const JoinSpec._();

  /// `INNER JOIN table ON condition`
  const factory JoinSpec.inner({required String table, required String on_}) =
      JoinSpec_Inner;

  /// `LEFT JOIN table ON condition`
  const factory JoinSpec.left({required String table, required String on_}) =
      JoinSpec_Left;

  /// Raw JOIN expression.
  const factory JoinSpec.raw({required String expression}) = JoinSpec_Raw;
}

@freezed
sealed class OrderBy with _$OrderBy {
  const OrderBy._();

  /// Order by column ascending.
  const factory OrderBy.asc({required String column}) = OrderBy_Asc;

  /// Order by column descending.
  const factory OrderBy.desc({required String column}) = OrderBy_Desc;

  /// Raw ORDER BY expression (e.g. `RANDOM()`).
  const factory OrderBy.raw({required String expression}) = OrderBy_Raw;
}

/// Paginated query result.
class Page {
  /// Rows for this page.
  final List<Map<String, SqlValue>> items;

  /// Total matching rows across all pages.
  final BigInt total;

  /// Total number of pages.
  final int totalPages;

  /// Current page index (0-based).
  final int page;

  /// Items per page.
  final int pageSize;

  const Page({
    required this.items,
    required this.total,
    required this.totalPages,
    required this.page,
    required this.pageSize,
  });

  @override
  int get hashCode =>
      items.hashCode ^
      total.hashCode ^
      totalPages.hashCode ^
      page.hashCode ^
      pageSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Page &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          total == other.total &&
          totalPages == other.totalPages &&
          page == other.page &&
          pageSize == other.pageSize;
}

/// Full query specification — built by Dart, executed by Rust.
///
/// Rust auto-injects `tenant_id = ?` and `deleted_at IS NULL`
/// outside any OR grouping, so tenant isolation cannot be bypassed.
///
/// - `conditions`: ANDed together (primary filter).
/// - `or_conditions`: each inner Vec is ANDed, outer groups are ORed.
///   If non-empty, generates: `(conditions) OR (group1) OR (group2)`.
class QuerySpec {
  final String table;

  /// Primary AND conditions (from `.where()` calls).
  final List<Condition> conditions;

  /// OR alternative groups (from `.orWhere()` calls).
  /// Each inner Vec is a group of AND conditions.
  final List<List<Condition>> orConditions;

  /// ORDER BY clauses, applied in order.
  final List<OrderBy> orderBy;

  /// Maximum rows to return.
  final int? limit;

  /// Rows to skip before returning.
  final int? offset;

  /// JOIN clauses.
  final List<JoinSpec> joins;

  /// Columns to select (empty = `*`).
  final List<String> columns;

  /// If true, include soft-deleted rows (skip `deleted_at IS NULL`).
  final bool includeDeleted;

  const QuerySpec({
    required this.table,
    required this.conditions,
    required this.orConditions,
    required this.orderBy,
    this.limit,
    this.offset,
    required this.joins,
    required this.columns,
    required this.includeDeleted,
  });

  @override
  int get hashCode =>
      table.hashCode ^
      conditions.hashCode ^
      orConditions.hashCode ^
      orderBy.hashCode ^
      limit.hashCode ^
      offset.hashCode ^
      joins.hashCode ^
      columns.hashCode ^
      includeDeleted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QuerySpec &&
          runtimeType == other.runtimeType &&
          table == other.table &&
          conditions == other.conditions &&
          orConditions == other.orConditions &&
          orderBy == other.orderBy &&
          limit == other.limit &&
          offset == other.offset &&
          joins == other.joins &&
          columns == other.columns &&
          includeDeleted == other.includeDeleted;
}

@freezed
sealed class SqlValue with _$SqlValue {
  const SqlValue._();

  /// SQL NULL.
  const factory SqlValue.null_() = SqlValue_Null;

  /// 64-bit signed integer.
  const factory SqlValue.integer(PlatformInt64 field0) = SqlValue_Integer;

  /// 64-bit floating point.
  const factory SqlValue.real(double field0) = SqlValue_Real;

  /// UTF-8 text string.
  const factory SqlValue.text(String field0) = SqlValue_Text;

  /// Binary blob.
  const factory SqlValue.blob(Uint8List field0) = SqlValue_Blob;
}

/// A single row update for batch operations.
class UpdateEntry {
  /// Row ID to update.
  final String id;

  /// Column → new value pairs.
  final Map<String, SqlValue> data;

  const UpdateEntry({required this.id, required this.data});

  @override
  int get hashCode => id.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          data == other.data;
}

/// Configuration for the IronVault database engine.
///
/// Controls connection pool sizes, cache settings, and SQLite PRAGMAs.
/// Use factory constructors for common configurations.
class VaultConfig {
  /// Number of concurrent read connections (default: 7).
  final int readPoolSize;

  /// Number of write connections (always 1 — do not increase).
  final int writePoolSize;

  /// Milliseconds to wait for a busy connection (default: 5000).
  final int busyTimeoutMs;

  /// SQLite page cache size in KB (default: 65536 = 64MB).
  final int cacheSizeKb;

  /// Memory-mapped I/O size in bytes (default: 256MB).
  final BigInt mmapSizeBytes;

  /// Maximum WAL journal size in bytes (default: 64MB).
  final BigInt journalSizeLimitBytes;

  /// Enable foreign key constraints (default: true).
  final bool foreignKeys;

  /// Enable WAL mode for concurrent reads (default: true).
  final bool walMode;

  const VaultConfig({
    required this.readPoolSize,
    required this.writePoolSize,
    required this.busyTimeoutMs,
    required this.cacheSizeKb,
    required this.mmapSizeBytes,
    required this.journalSizeLimitBytes,
    required this.foreignKeys,
    required this.walMode,
  });

  static Future<VaultConfig> default_() =>
      RustLib.instance.api.crateApiTypesVaultConfigDefault();

  /// Development defaults — smaller cache, suitable for debugging.
  static VaultConfig development() =>
      RustLib.instance.api.crateApiTypesVaultConfigDevelopment();

  /// Low-memory defaults — 8MB cache, 3 readers. For budget devices.
  static VaultConfig lowMemory() =>
      RustLib.instance.api.crateApiTypesVaultConfigLowMemory();

  /// Production defaults — 64MB cache, 7 readers, WAL mode.
  static VaultConfig production() =>
      RustLib.instance.api.crateApiTypesVaultConfigProduction();

  /// Test defaults — small pool, minimal cache, no WAL.
  static VaultConfig testConfig() =>
      RustLib.instance.api.crateApiTypesVaultConfigTestConfig();

  @override
  int get hashCode =>
      readPoolSize.hashCode ^
      writePoolSize.hashCode ^
      busyTimeoutMs.hashCode ^
      cacheSizeKb.hashCode ^
      mmapSizeBytes.hashCode ^
      journalSizeLimitBytes.hashCode ^
      foreignKeys.hashCode ^
      walMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultConfig &&
          runtimeType == other.runtimeType &&
          readPoolSize == other.readPoolSize &&
          writePoolSize == other.writePoolSize &&
          busyTimeoutMs == other.busyTimeoutMs &&
          cacheSizeKb == other.cacheSizeKb &&
          mmapSizeBytes == other.mmapSizeBytes &&
          journalSizeLimitBytes == other.journalSizeLimitBytes &&
          foreignKeys == other.foreignKeys &&
          walMode == other.walMode;
}

/// Database statistics snapshot.
class VaultStats {
  /// Total database file size in bytes.
  final PlatformInt64 dbSizeBytes;

  /// WAL file size in bytes (0 if no WAL).
  final PlatformInt64 walSizeBytes;

  /// Number of user tables (excludes sqlite_* internal tables).
  final int totalTables;

  /// Current migration version (0 if no migrations applied yet).
  final int migrationVersion;

  /// Database page count.
  final PlatformInt64 pageCount;

  /// Database page size in bytes.
  final PlatformInt64 pageSize;

  const VaultStats({
    required this.dbSizeBytes,
    required this.walSizeBytes,
    required this.totalTables,
    required this.migrationVersion,
    required this.pageCount,
    required this.pageSize,
  });

  @override
  int get hashCode =>
      dbSizeBytes.hashCode ^
      walSizeBytes.hashCode ^
      totalTables.hashCode ^
      migrationVersion.hashCode ^
      pageCount.hashCode ^
      pageSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultStats &&
          runtimeType == other.runtimeType &&
          dbSizeBytes == other.dbSizeBytes &&
          walSizeBytes == other.walSizeBytes &&
          totalTables == other.totalTables &&
          migrationVersion == other.migrationVersion &&
          pageCount == other.pageCount &&
          pageSize == other.pageSize;
}
