// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

@freezed
sealed class AggExpr with _$AggExpr {
  const AggExpr._();

  /// `COUNT(column) AS alias`
  const factory AggExpr.count({required String column, required String alias}) =
      AggExpr_Count;

  /// `SUM(column) AS alias`
  const factory AggExpr.sum({required String column, required String alias}) =
      AggExpr_Sum;

  /// `AVG(column) AS alias`
  const factory AggExpr.avg({required String column, required String alias}) =
      AggExpr_Avg;

  /// `MIN(column) AS alias`
  const factory AggExpr.min({required String column, required String alias}) =
      AggExpr_Min;

  /// `MAX(column) AS alias`
  const factory AggExpr.max({required String column, required String alias}) =
      AggExpr_Max;
}

/// A single audit log entry.
class AuditEntry {
  /// Unique entry ID.
  final String id;

  /// Table that was modified.
  final String tableName;

  /// ID of the row that was modified.
  final String rowId;

  /// Operation: INSERT, UPDATE, DELETE, HARD_DELETE.
  final String operation;

  /// Who performed the operation (set via `set_actor()`).
  final String actorId;

  /// Tenant that owns this entry.
  final String tenantId;

  /// JSON snapshot of the row before the change (None for INSERT).
  final String? beforeJson;

  /// JSON snapshot of the row after the change (None for DELETE).
  final String? afterJson;

  /// JSON array of field names that changed (None for INSERT/DELETE).
  final String? changedFields;

  /// Epoch milliseconds when the entry was created.
  final PlatformInt64 timestamp;

  /// HMAC-SHA256 checksum for tamper detection.
  final String checksum;

  const AuditEntry({
    required this.id,
    required this.tableName,
    required this.rowId,
    required this.operation,
    required this.actorId,
    required this.tenantId,
    this.beforeJson,
    this.afterJson,
    this.changedFields,
    required this.timestamp,
    required this.checksum,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      tableName.hashCode ^
      rowId.hashCode ^
      operation.hashCode ^
      actorId.hashCode ^
      tenantId.hashCode ^
      beforeJson.hashCode ^
      afterJson.hashCode ^
      changedFields.hashCode ^
      timestamp.hashCode ^
      checksum.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuditEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          tableName == other.tableName &&
          rowId == other.rowId &&
          operation == other.operation &&
          actorId == other.actorId &&
          tenantId == other.tenantId &&
          beforeJson == other.beforeJson &&
          afterJson == other.afterJson &&
          changedFields == other.changedFields &&
          timestamp == other.timestamp &&
          checksum == other.checksum;
}

/// Result of audit log integrity verification.
class AuditIntegrityReport {
  /// Total entries checked.
  final BigInt totalChecked;

  /// True if all checksums match.
  final bool isClean;

  /// IDs of entries with mismatched checksums.
  final List<String> tamperedIds;

  const AuditIntegrityReport({
    required this.totalChecked,
    required this.isClean,
    required this.tamperedIds,
  });

  @override
  int get hashCode =>
      totalChecked.hashCode ^ isClean.hashCode ^ tamperedIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuditIntegrityReport &&
          runtimeType == other.runtimeType &&
          totalChecked == other.totalChecked &&
          isClean == other.isClean &&
          tamperedIds == other.tamperedIds;
}

/// Result of a backup operation.
class BackupResult {
  /// Path to the backup file.
  final String path;

  /// Size of the backup file in bytes.
  final BigInt sizeBytes;

  /// BLAKE3 checksum hex string (for verification on restore).
  final String checksum;

  /// Whether compression was applied.
  final bool compressed;

  /// Whether encryption was applied.
  final bool encrypted;

  const BackupResult({
    required this.path,
    required this.sizeBytes,
    required this.checksum,
    required this.compressed,
    required this.encrypted,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      sizeBytes.hashCode ^
      checksum.hashCode ^
      compressed.hashCode ^
      encrypted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupResult &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          sizeBytes == other.sizeBytes &&
          checksum == other.checksum &&
          compressed == other.compressed &&
          encrypted == other.encrypted;
}

/// Result of backup verification (without restoring).
class BackupVerifyReport {
  /// Whether the BLAKE3 checksum matches.
  final bool checksumOk;

  /// Whether the backup can be decrypted.
  final bool decryptOk;

  /// Whether the decompressed data is valid.
  final bool decompressOk;

  const BackupVerifyReport({
    required this.checksumOk,
    required this.decryptOk,
    required this.decompressOk,
  });

  @override
  int get hashCode =>
      checksumOk.hashCode ^ decryptOk.hashCode ^ decompressOk.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupVerifyReport &&
          runtimeType == other.runtimeType &&
          checksumOk == other.checksumOk &&
          decryptOk == other.decryptOk &&
          decompressOk == other.decompressOk;
}

/// WAL checkpoint mode.
enum CheckpointMode {
  /// Checkpoint as many WAL pages as possible without waiting.
  passive,

  /// Checkpoint all WAL pages, waiting for readers to finish.
  full,

  /// Like Full, then restart the WAL file from the beginning.
  restart,

  /// Like Restart, then truncate the WAL file to zero bytes.
  truncate,
}

/// Result of a WAL checkpoint operation.
class CheckpointResult {
  /// Total number of WAL pages.
  final int walPages;

  /// Number of pages successfully checkpointed.
  final int checkpointedPages;

  const CheckpointResult({
    required this.walPages,
    required this.checkpointedPages,
  });

  @override
  int get hashCode => walPages.hashCode ^ checkpointedPages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CheckpointResult &&
          runtimeType == other.runtimeType &&
          walPages == other.walPages &&
          checkpointedPages == other.checkpointedPages;
}

@freezed
sealed class Condition with _$Condition {
  const Condition._();

  /// `column = value`
  const factory Condition.eq({
    required String column,
    required SqlValue value,
  }) = Condition_Eq;

  /// `column != value`
  const factory Condition.notEq({
    required String column,
    required SqlValue value,
  }) = Condition_NotEq;

  /// `column > value`
  const factory Condition.gt({
    required String column,
    required SqlValue value,
  }) = Condition_Gt;

  /// `column >= value`
  const factory Condition.gte({
    required String column,
    required SqlValue value,
  }) = Condition_Gte;

  /// `column < value`
  const factory Condition.lt({
    required String column,
    required SqlValue value,
  }) = Condition_Lt;

  /// `column <= value`
  const factory Condition.lte({
    required String column,
    required SqlValue value,
  }) = Condition_Lte;

  /// `column LIKE pattern` (use % and _ wildcards)
  const factory Condition.like({
    required String column,
    required String pattern,
  }) = Condition_Like;

  /// `column BETWEEN low AND high`
  const factory Condition.between({
    required String column,
    required SqlValue low,
    required SqlValue high,
  }) = Condition_Between;

  /// `column IN (v1, v2, ...)`
  const factory Condition.in_({
    required String column,
    required List<SqlValue> values,
  }) = Condition_In;

  /// `column NOT IN (v1, v2, ...)`
  const factory Condition.notIn({
    required String column,
    required List<SqlValue> values,
  }) = Condition_NotIn;

  /// `column IS NULL`
  const factory Condition.isNull({required String column}) = Condition_IsNull;

  /// `column IS NOT NULL`
  const factory Condition.isNotNull({required String column}) =
      Condition_IsNotNull;

  /// Raw SQL fragment with parameterized values.
  /// The SQL is inserted as-is — caller is responsible for safety.
  const factory Condition.raw({
    required String sql,
    required List<SqlValue> params,
  }) = Condition_Raw;
}

/// Strategy for resolving sync conflicts.
enum ConflictResolution {
  /// Most recent timestamp wins.
  lastWriteWins,

  /// Local data always kept.
  localWins,

  /// Remote data always applied.
  remoteWins,
}

/// Export format for table data.
enum ExportFormat {
  /// RFC 4180 CSV with headers.
  csv,

  /// JSON array of objects.
  json,

  /// One JSON object per line.
  jsonl,
}

/// A hybrid search result combining FTS and semantic scores.
class HybridHit {
  /// Row ID.
  final String id;

  /// Table name.
  final String table;

  /// Combined score.
  final double score;

  /// FTS component score (normalized 0–1).
  final double ftsScore;

  /// Semantic component score (cosine 0–1).
  final double semanticScore;

  /// Snippet from FTS (if available).
  final String snippet;

  const HybridHit({
    required this.id,
    required this.table,
    required this.score,
    required this.ftsScore,
    required this.semanticScore,
    required this.snippet,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      table.hashCode ^
      score.hashCode ^
      ftsScore.hashCode ^
      semanticScore.hashCode ^
      snippet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HybridHit &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          table == other.table &&
          score == other.score &&
          ftsScore == other.ftsScore &&
          semanticScore == other.semanticScore &&
          snippet == other.snippet;
}

/// Statistics about a search index.
class IndexStats {
  /// Number of indexed documents.
  final BigInt numDocs;

  /// Number of segments in the index.
  final BigInt numSegments;

  /// Total size of the index directory in bytes.
  final BigInt sizeBytes;

  const IndexStats({
    required this.numDocs,
    required this.numSegments,
    required this.sizeBytes,
  });

  @override
  int get hashCode =>
      numDocs.hashCode ^ numSegments.hashCode ^ sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IndexStats &&
          runtimeType == other.runtimeType &&
          numDocs == other.numDocs &&
          numSegments == other.numSegments &&
          sizeBytes == other.sizeBytes;
}

/// Result of a database integrity check.
class IntegrityReport {
  /// True if no corruption detected.
  final bool isClean;

  /// List of error messages (empty if clean).
  final List<String> errors;

  const IntegrityReport({required this.isClean, required this.errors});

  @override
  int get hashCode => isClean.hashCode ^ errors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IntegrityReport &&
          runtimeType == other.runtimeType &&
          isClean == other.isClean &&
          errors == other.errors;
}

@freezed
sealed class JoinSpec with _$JoinSpec {
  const JoinSpec._();

  /// `INNER JOIN table ON condition`
  const factory JoinSpec.inner({required String table, required String on_}) =
      JoinSpec_Inner;

  /// `LEFT JOIN table ON condition`
  const factory JoinSpec.left({required String table, required String on_}) =
      JoinSpec_Left;

  /// Raw JOIN expression.
  const factory JoinSpec.raw({required String expression}) = JoinSpec_Raw;
}

/// A record from the _migrations tracking table.
class MigrationRecord {
  /// Migration version.
  final int version;

  /// Migration name.
  final String name;

  /// SHA-256 checksum of the `up` SQL.
  final String checksum;

  /// Epoch milliseconds when applied.
  final PlatformInt64 appliedAt;

  /// Duration in milliseconds to apply.
  final PlatformInt64 durationMs;

  const MigrationRecord({
    required this.version,
    required this.name,
    required this.checksum,
    required this.appliedAt,
    required this.durationMs,
  });

  @override
  int get hashCode =>
      version.hashCode ^
      name.hashCode ^
      checksum.hashCode ^
      appliedAt.hashCode ^
      durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MigrationRecord &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          name == other.name &&
          checksum == other.checksum &&
          appliedAt == other.appliedAt &&
          durationMs == other.durationMs;
}

/// Report returned after running migrations.
class MigrationReport {
  /// Versions that were applied in this run.
  final Uint32List applied;

  /// Versions that were already applied (skipped).
  final Uint32List skipped;

  /// Current schema version after this run (0 if no migrations exist).
  final int currentVersion;

  const MigrationReport({
    required this.applied,
    required this.skipped,
    required this.currentVersion,
  });

  @override
  int get hashCode =>
      applied.hashCode ^ skipped.hashCode ^ currentVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MigrationReport &&
          runtimeType == other.runtimeType &&
          applied == other.applied &&
          skipped == other.skipped &&
          currentVersion == other.currentVersion;
}

@freezed
sealed class Op with _$Op {
  const Op._();

  /// Insert a row (auto UUID, auto timestamps, auto tenant_id).
  const factory Op.insert({
    required String table,
    required Map<String, SqlValue> data,
  }) = Op_Insert;

  /// Update a row by id (enforces tenant_id + soft-delete guard).
  const factory Op.update({
    required String table,
    required String id,
    required Map<String, SqlValue> data,
  }) = Op_Update;

  /// Upsert (insert or update on conflict).
  const factory Op.upsert({
    required String table,
    required Map<String, SqlValue> data,
    required String conflictColumn,
  }) = Op_Upsert;

  /// Soft-delete a row (sets deleted_at).
  const factory Op.delete({required String table, required String id}) =
      Op_Delete;

  /// Permanently delete a row.
  const factory Op.hardDelete({required String table, required String id}) =
      Op_HardDelete;

  /// Raw SQL with parameterized values (escape hatch).
  const factory Op.raw({required String sql, required List<SqlValue> params}) =
      Op_Raw;

  /// Create a savepoint (nested transaction marker).
  const factory Op.savepoint({required String name}) = Op_Savepoint;

  /// Release (commit) a savepoint.
  const factory Op.releaseSavepoint({required String name}) =
      Op_ReleaseSavepoint;

  /// Rollback to a savepoint (partial undo).
  const factory Op.rollbackToSavepoint({required String name}) =
      Op_RollbackToSavepoint;
}

@freezed
sealed class OrderBy with _$OrderBy {
  const OrderBy._();

  /// Order by column ascending.
  const factory OrderBy.asc({required String column}) = OrderBy_Asc;

  /// Order by column descending.
  const factory OrderBy.desc({required String column}) = OrderBy_Desc;

  /// Raw ORDER BY expression (e.g. `RANDOM()`).
  const factory OrderBy.raw({required String expression}) = OrderBy_Raw;
}

/// Paginated query result.
class Page {
  /// Rows for this page.
  final List<Map<String, SqlValue>> items;

  /// Total matching rows across all pages.
  final BigInt total;

  /// Total number of pages.
  final int totalPages;

  /// Current page index (0-based).
  final int page;

  /// Items per page.
  final int pageSize;

  const Page({
    required this.items,
    required this.total,
    required this.totalPages,
    required this.page,
    required this.pageSize,
  });

  @override
  int get hashCode =>
      items.hashCode ^
      total.hashCode ^
      totalPages.hashCode ^
      page.hashCode ^
      pageSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Page &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          total == other.total &&
          totalPages == other.totalPages &&
          page == other.page &&
          pageSize == other.pageSize;
}

/// Full query specification — built by Dart, executed by Rust.
///
/// Rust auto-injects `tenant_id = ?` and `deleted_at IS NULL`
/// outside any OR grouping, so tenant isolation cannot be bypassed.
///
/// - `conditions`: ANDed together (primary filter).
/// - `or_conditions`: each inner Vec is ANDed, outer groups are ORed.
///   If non-empty, generates: `(conditions) OR (group1) OR (group2)`.
class QuerySpec {
  final String table;

  /// Primary AND conditions (from `.where()` calls).
  final List<Condition> conditions;

  /// OR alternative groups (from `.orWhere()` calls).
  /// Each inner Vec is a group of AND conditions.
  final List<List<Condition>> orConditions;

  /// ORDER BY clauses, applied in order.
  final List<OrderBy> orderBy;

  /// Maximum rows to return.
  final int? limit;

  /// Rows to skip before returning.
  final int? offset;

  /// JOIN clauses.
  final List<JoinSpec> joins;

  /// Columns to select (empty = `*`).
  final List<String> columns;

  /// If true, include soft-deleted rows (skip `deleted_at IS NULL`).
  final bool includeDeleted;

  const QuerySpec({
    required this.table,
    required this.conditions,
    required this.orConditions,
    required this.orderBy,
    this.limit,
    this.offset,
    required this.joins,
    required this.columns,
    required this.includeDeleted,
  });

  @override
  int get hashCode =>
      table.hashCode ^
      conditions.hashCode ^
      orConditions.hashCode ^
      orderBy.hashCode ^
      limit.hashCode ^
      offset.hashCode ^
      joins.hashCode ^
      columns.hashCode ^
      includeDeleted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QuerySpec &&
          runtimeType == other.runtimeType &&
          table == other.table &&
          conditions == other.conditions &&
          orConditions == other.orConditions &&
          orderBy == other.orderBy &&
          limit == other.limit &&
          offset == other.offset &&
          joins == other.joins &&
          columns == other.columns &&
          includeDeleted == other.includeDeleted;
}

/// Result of a restore operation.
class RestoreResult {
  /// Number of pages restored.
  final BigInt pagesRestored;

  /// Whether integrity check passed after restore.
  final bool integrityOk;

  const RestoreResult({required this.pagesRestored, required this.integrityOk});

  @override
  int get hashCode => pagesRestored.hashCode ^ integrityOk.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RestoreResult &&
          runtimeType == other.runtimeType &&
          pagesRestored == other.pagesRestored &&
          integrityOk == other.integrityOk;
}

/// A field definition for building a search index.
class SearchField {
  /// Column name in the database.
  final String name;

  /// Relevance weight (default 1.0, higher = more important).
  final double weight;

  /// Whether this field is stored in the index (returned in results).
  final bool stored;

  const SearchField({
    required this.name,
    required this.weight,
    required this.stored,
  });

  @override
  int get hashCode => name.hashCode ^ weight.hashCode ^ stored.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchField &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          weight == other.weight &&
          stored == other.stored;
}

/// A single search result.
class SearchHit {
  /// Row ID from the database.
  final String id;

  /// Table the result came from.
  final String table;

  /// Relevance score (higher = more relevant).
  final double score;

  /// Highlighted snippet (HTML with `<b>` tags).
  final String snippet;

  const SearchHit({
    required this.id,
    required this.table,
    required this.score,
    required this.snippet,
  });

  @override
  int get hashCode =>
      id.hashCode ^ table.hashCode ^ score.hashCode ^ snippet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchHit &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          table == other.table &&
          score == other.score &&
          snippet == other.snippet;
}

/// A semantic search result with cosine similarity score.
class SemanticHit {
  /// Row ID.
  final String id;

  /// Cosine similarity score (0.0 to 1.0).
  final double score;

  const SemanticHit({required this.id, required this.score});

  @override
  int get hashCode => id.hashCode ^ score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SemanticHit &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          score == other.score;
}

@freezed
sealed class SqlValue with _$SqlValue {
  const SqlValue._();

  /// SQL NULL.
  const factory SqlValue.null_() = SqlValue_Null;

  /// 64-bit signed integer.
  const factory SqlValue.integer(PlatformInt64 field0) = SqlValue_Integer;

  /// 64-bit floating point.
  const factory SqlValue.real(double field0) = SqlValue_Real;

  /// UTF-8 text string.
  const factory SqlValue.text(String field0) = SqlValue_Text;

  /// Binary blob.
  const factory SqlValue.blob(Uint8List field0) = SqlValue_Blob;
}

/// Result of applying incoming sync records.
class SyncApplyResult {
  final int applied;
  final int conflicts;
  final int skipped;

  const SyncApplyResult({
    required this.applied,
    required this.conflicts,
    required this.skipped,
  });

  @override
  int get hashCode => applied.hashCode ^ conflicts.hashCode ^ skipped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncApplyResult &&
          runtimeType == other.runtimeType &&
          applied == other.applied &&
          conflicts == other.conflicts &&
          skipped == other.skipped;
}

/// A detected sync conflict between local and remote data.
class SyncConflict {
  final String id;
  final String tableName;
  final String rowId;
  final String localData;
  final String remoteData;
  final String localClock;
  final String remoteClock;
  final PlatformInt64 detectedAt;
  final bool resolved;

  const SyncConflict({
    required this.id,
    required this.tableName,
    required this.rowId,
    required this.localData,
    required this.remoteData,
    required this.localClock,
    required this.remoteClock,
    required this.detectedAt,
    required this.resolved,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      tableName.hashCode ^
      rowId.hashCode ^
      localData.hashCode ^
      remoteData.hashCode ^
      localClock.hashCode ^
      remoteClock.hashCode ^
      detectedAt.hashCode ^
      resolved.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncConflict &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          tableName == other.tableName &&
          rowId == other.rowId &&
          localData == other.localData &&
          remoteData == other.remoteData &&
          localClock == other.localClock &&
          remoteClock == other.remoteClock &&
          detectedAt == other.detectedAt &&
          resolved == other.resolved;
}

/// A batch of sync records to push or pull.
class SyncDelta {
  final List<SyncRecord> records;

  const SyncDelta({required this.records});

  @override
  int get hashCode => records.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncDelta &&
          runtimeType == other.runtimeType &&
          records == other.records;
}

/// A record in the sync outbox (pending upload to server).
class SyncRecord {
  final String id;
  final String tableName;
  final String rowId;
  final String operation;
  final String payload;
  final String vectorClock;
  final PlatformInt64 createdAt;
  final PlatformInt64? syncedAt;
  final int attempts;
  final String tenantId;

  const SyncRecord({
    required this.id,
    required this.tableName,
    required this.rowId,
    required this.operation,
    required this.payload,
    required this.vectorClock,
    required this.createdAt,
    this.syncedAt,
    required this.attempts,
    required this.tenantId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      tableName.hashCode ^
      rowId.hashCode ^
      operation.hashCode ^
      payload.hashCode ^
      vectorClock.hashCode ^
      createdAt.hashCode ^
      syncedAt.hashCode ^
      attempts.hashCode ^
      tenantId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          tableName == other.tableName &&
          rowId == other.rowId &&
          operation == other.operation &&
          payload == other.payload &&
          vectorClock == other.vectorClock &&
          createdAt == other.createdAt &&
          syncedAt == other.syncedAt &&
          attempts == other.attempts &&
          tenantId == other.tenantId;
}

/// Result of a multi-operation transaction.
class TransactionResult {
  /// IDs of all inserted rows (in op order).
  final List<String> insertedIds;

  /// Names of all tables affected by the transaction.
  final List<String> affectedTables;

  /// Total number of rows affected across all operations.
  final BigInt rowsAffected;

  const TransactionResult({
    required this.insertedIds,
    required this.affectedTables,
    required this.rowsAffected,
  });

  @override
  int get hashCode =>
      insertedIds.hashCode ^ affectedTables.hashCode ^ rowsAffected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionResult &&
          runtimeType == other.runtimeType &&
          insertedIds == other.insertedIds &&
          affectedTables == other.affectedTables &&
          rowsAffected == other.rowsAffected;
}

/// A single row update for batch operations.
class UpdateEntry {
  /// Row ID to update.
  final String id;

  /// Column → new value pairs.
  final Map<String, SqlValue> data;

  const UpdateEntry({required this.id, required this.data});

  @override
  int get hashCode => id.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          data == other.data;
}

/// Configuration for the IronVault database engine.
///
/// Controls connection pool sizes, cache settings, and SQLite PRAGMAs.
/// Use factory constructors for common configurations.
class VaultConfig {
  /// Number of concurrent read connections (default: 7).
  final int readPoolSize;

  /// Number of write connections (always 1 — do not increase).
  final int writePoolSize;

  /// Milliseconds to wait for a busy connection (default: 5000).
  final int busyTimeoutMs;

  /// SQLite page cache size in KB (default: 65536 = 64MB).
  final int cacheSizeKb;

  /// Memory-mapped I/O size in bytes (default: 256MB).
  final BigInt mmapSizeBytes;

  /// Maximum WAL journal size in bytes (default: 64MB).
  final BigInt journalSizeLimitBytes;

  /// Enable foreign key constraints (default: true).
  final bool foreignKeys;

  /// Enable WAL mode for concurrent reads (default: true).
  final bool walMode;

  const VaultConfig({
    required this.readPoolSize,
    required this.writePoolSize,
    required this.busyTimeoutMs,
    required this.cacheSizeKb,
    required this.mmapSizeBytes,
    required this.journalSizeLimitBytes,
    required this.foreignKeys,
    required this.walMode,
  });

  static Future<VaultConfig> default_() =>
      RustLib.instance.api.crateApiTypesVaultConfigDefault();

  /// Development defaults — smaller cache, suitable for debugging.
  static VaultConfig development() =>
      RustLib.instance.api.crateApiTypesVaultConfigDevelopment();

  /// Low-memory defaults — 8MB cache, 3 readers. For budget devices.
  static VaultConfig lowMemory() =>
      RustLib.instance.api.crateApiTypesVaultConfigLowMemory();

  /// Production defaults — 64MB cache, 7 readers, WAL mode.
  static VaultConfig production() =>
      RustLib.instance.api.crateApiTypesVaultConfigProduction();

  /// Test defaults — small pool, minimal cache, no WAL.
  static VaultConfig testConfig() =>
      RustLib.instance.api.crateApiTypesVaultConfigTestConfig();

  @override
  int get hashCode =>
      readPoolSize.hashCode ^
      writePoolSize.hashCode ^
      busyTimeoutMs.hashCode ^
      cacheSizeKb.hashCode ^
      mmapSizeBytes.hashCode ^
      journalSizeLimitBytes.hashCode ^
      foreignKeys.hashCode ^
      walMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultConfig &&
          runtimeType == other.runtimeType &&
          readPoolSize == other.readPoolSize &&
          writePoolSize == other.writePoolSize &&
          busyTimeoutMs == other.busyTimeoutMs &&
          cacheSizeKb == other.cacheSizeKb &&
          mmapSizeBytes == other.mmapSizeBytes &&
          journalSizeLimitBytes == other.journalSizeLimitBytes &&
          foreignKeys == other.foreignKeys &&
          walMode == other.walMode;
}

/// A single versioned schema migration.
///
/// Migrations are applied in version order. Each migration's `up` SQL
/// is checksummed (SHA-256) and the checksum is stored in the database.
/// If a previously-applied migration's SQL has been altered, IronVault
/// detects the tampering and refuses to proceed.
class VaultMigration {
  /// Unique version number (must be > 0, applied in ascending order).
  final int version;

  /// Human-readable name for logging.
  final String name;

  /// SQL to apply this migration (executed in a transaction).
  final String up;

  /// SQL to reverse this migration (None = irreversible).
  final String? down;

  const VaultMigration({
    required this.version,
    required this.name,
    required this.up,
    this.down,
  });

  @override
  int get hashCode =>
      version.hashCode ^ name.hashCode ^ up.hashCode ^ down.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultMigration &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          name == other.name &&
          up == other.up &&
          down == other.down;
}

/// Database statistics snapshot.
class VaultStats {
  /// Total database file size in bytes.
  final PlatformInt64 dbSizeBytes;

  /// WAL file size in bytes (0 if no WAL).
  final PlatformInt64 walSizeBytes;

  /// Number of user tables (excludes sqlite_* internal tables).
  final int totalTables;

  /// Current migration version (0 if no migrations applied yet).
  final int migrationVersion;

  /// Database page count.
  final PlatformInt64 pageCount;

  /// Database page size in bytes.
  final PlatformInt64 pageSize;

  const VaultStats({
    required this.dbSizeBytes,
    required this.walSizeBytes,
    required this.totalTables,
    required this.migrationVersion,
    required this.pageCount,
    required this.pageSize,
  });

  @override
  int get hashCode =>
      dbSizeBytes.hashCode ^
      walSizeBytes.hashCode ^
      totalTables.hashCode ^
      migrationVersion.hashCode ^
      pageCount.hashCode ^
      pageSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultStats &&
          runtimeType == other.runtimeType &&
          dbSizeBytes == other.dbSizeBytes &&
          walSizeBytes == other.walSizeBytes &&
          totalTables == other.totalTables &&
          migrationVersion == other.migrationVersion &&
          pageCount == other.pageCount &&
          pageSize == other.pageSize;
}

/// Vector clock for causality tracking in sync.
///
/// Maps node_id → counter. Used to detect concurrent edits
/// and determine happens-before relationships.
class VectorClock {
  /// Node ID → logical timestamp.
  final Map<String, BigInt> clocks;

  const VectorClock({required this.clocks});

  @override
  int get hashCode => clocks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VectorClock &&
          runtimeType == other.runtimeType &&
          clocks == other.clocks;
}
