// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// WAL checkpoint mode.
enum CheckpointMode {
  /// Checkpoint as many WAL pages as possible without waiting.
  passive,

  /// Checkpoint all WAL pages, waiting for readers to finish.
  full,

  /// Like Full, then restart the WAL file from the beginning.
  restart,

  /// Like Restart, then truncate the WAL file to zero bytes.
  truncate,
}

/// Result of a WAL checkpoint operation.
class CheckpointResult {
  /// Total number of WAL pages.
  final int walPages;

  /// Number of pages successfully checkpointed.
  final int checkpointedPages;

  const CheckpointResult({
    required this.walPages,
    required this.checkpointedPages,
  });

  @override
  int get hashCode => walPages.hashCode ^ checkpointedPages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CheckpointResult &&
          runtimeType == other.runtimeType &&
          walPages == other.walPages &&
          checkpointedPages == other.checkpointedPages;
}

/// Result of a database integrity check.
class IntegrityReport {
  /// True if no corruption detected.
  final bool isClean;

  /// List of error messages (empty if clean).
  final List<String> errors;

  const IntegrityReport({required this.isClean, required this.errors});

  @override
  int get hashCode => isClean.hashCode ^ errors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IntegrityReport &&
          runtimeType == other.runtimeType &&
          isClean == other.isClean &&
          errors == other.errors;
}

@freezed
sealed class SqlValue with _$SqlValue {
  const SqlValue._();

  /// SQL NULL.
  const factory SqlValue.null_() = SqlValue_Null;

  /// 64-bit signed integer.
  const factory SqlValue.integer(PlatformInt64 field0) = SqlValue_Integer;

  /// 64-bit floating point.
  const factory SqlValue.real(double field0) = SqlValue_Real;

  /// UTF-8 text string.
  const factory SqlValue.text(String field0) = SqlValue_Text;

  /// Binary blob.
  const factory SqlValue.blob(Uint8List field0) = SqlValue_Blob;
}

/// Configuration for the IronVault database engine.
///
/// Controls connection pool sizes, cache settings, and SQLite PRAGMAs.
/// Use factory constructors for common configurations.
class VaultConfig {
  /// Number of concurrent read connections (default: 7).
  final int readPoolSize;

  /// Number of write connections (always 1 — do not increase).
  final int writePoolSize;

  /// Milliseconds to wait for a busy connection (default: 5000).
  final int busyTimeoutMs;

  /// SQLite page cache size in KB (default: 65536 = 64MB).
  final int cacheSizeKb;

  /// Memory-mapped I/O size in bytes (default: 256MB).
  final BigInt mmapSizeBytes;

  /// Maximum WAL journal size in bytes (default: 64MB).
  final BigInt journalSizeLimitBytes;

  /// Enable foreign key constraints (default: true).
  final bool foreignKeys;

  /// Enable WAL mode for concurrent reads (default: true).
  final bool walMode;

  const VaultConfig({
    required this.readPoolSize,
    required this.writePoolSize,
    required this.busyTimeoutMs,
    required this.cacheSizeKb,
    required this.mmapSizeBytes,
    required this.journalSizeLimitBytes,
    required this.foreignKeys,
    required this.walMode,
  });

  static Future<VaultConfig> default_() =>
      RustLib.instance.api.crateApiTypesVaultConfigDefault();

  /// Development defaults — smaller cache, suitable for debugging.
  static VaultConfig development() =>
      RustLib.instance.api.crateApiTypesVaultConfigDevelopment();

  /// Low-memory defaults — 8MB cache, 3 readers. For budget devices.
  static VaultConfig lowMemory() =>
      RustLib.instance.api.crateApiTypesVaultConfigLowMemory();

  /// Production defaults — 64MB cache, 7 readers, WAL mode.
  static VaultConfig production() =>
      RustLib.instance.api.crateApiTypesVaultConfigProduction();

  /// Test defaults — small pool, minimal cache, no WAL.
  static VaultConfig testConfig() =>
      RustLib.instance.api.crateApiTypesVaultConfigTestConfig();

  @override
  int get hashCode =>
      readPoolSize.hashCode ^
      writePoolSize.hashCode ^
      busyTimeoutMs.hashCode ^
      cacheSizeKb.hashCode ^
      mmapSizeBytes.hashCode ^
      journalSizeLimitBytes.hashCode ^
      foreignKeys.hashCode ^
      walMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultConfig &&
          runtimeType == other.runtimeType &&
          readPoolSize == other.readPoolSize &&
          writePoolSize == other.writePoolSize &&
          busyTimeoutMs == other.busyTimeoutMs &&
          cacheSizeKb == other.cacheSizeKb &&
          mmapSizeBytes == other.mmapSizeBytes &&
          journalSizeLimitBytes == other.journalSizeLimitBytes &&
          foreignKeys == other.foreignKeys &&
          walMode == other.walMode;
}

/// Database statistics snapshot.
class VaultStats {
  /// Total database file size in bytes.
  final PlatformInt64 dbSizeBytes;

  /// WAL file size in bytes (0 if no WAL).
  final PlatformInt64 walSizeBytes;

  /// Number of user tables (excludes sqlite_* internal tables).
  final int totalTables;

  /// Current migration version (0 if no migrations applied yet).
  final int migrationVersion;

  /// Database page count.
  final PlatformInt64 pageCount;

  /// Database page size in bytes.
  final PlatformInt64 pageSize;

  const VaultStats({
    required this.dbSizeBytes,
    required this.walSizeBytes,
    required this.totalTables,
    required this.migrationVersion,
    required this.pageCount,
    required this.pageSize,
  });

  @override
  int get hashCode =>
      dbSizeBytes.hashCode ^
      walSizeBytes.hashCode ^
      totalTables.hashCode ^
      migrationVersion.hashCode ^
      pageCount.hashCode ^
      pageSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultStats &&
          runtimeType == other.runtimeType &&
          dbSizeBytes == other.dbSizeBytes &&
          walSizeBytes == other.walSizeBytes &&
          totalTables == other.totalTables &&
          migrationVersion == other.migrationVersion &&
          pageCount == other.pageCount &&
          pageSize == other.pageSize;
}
