// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `checkpoint_internal`, `ensure_open`, `from_rusqlite_value`, `to_rusqlite_value`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PragmaCustomizer`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `on_acquire`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<IronVaultDb>>
abstract class IronVaultDb implements RustOpaqueInterface {
  /// Trigger a WAL checkpoint.
  ///
  /// Returns the number of WAL pages and how many were successfully
  /// checkpointed. Call periodically (every ~15 min) and on app
  /// background to keep the WAL file from growing unbounded.
  Future<CheckpointResult> checkpoint({required CheckpointMode mode});

  /// Checkpoint WAL and mark the database as closed.
  ///
  /// After this call, all methods will return an error.
  /// Connection cleanup happens when the Dart GC drops this object.
  Future<void> close();

  /// Execute a write statement (INSERT, UPDATE, DELETE, DDL).
  ///
  /// Uses the **write** connection pool (serialized).
  /// Returns the number of rows affected.
  /// Parameters are bound positionally (`?1`, `?2`, ...).
  Future<BigInt> executeRaw({
    required String sql,
    required List<SqlValue> params,
  });

  /// Get the filesystem path of the database file.
  Future<String> getPath();

  /// Get the tenant ID bound to this database instance.
  Future<String> getTenantId();

  /// Run SQLite integrity check.
  ///
  /// Scans the entire database for corruption. Returns clean=true if
  /// no issues found. Can be slow on large databases — run sparingly.
  Future<IntegrityReport> integrityCheck();

  /// Open or create an encrypted database.
  ///
  /// - `path`: absolute filesystem path to the `.db` file.
  ///   Parent directory is created if it doesn't exist.
  /// - `encryption_key`: exactly 32 bytes (AES-256 key).
  ///   Derive with Argon2id; zero the Dart-side copy after this call.
  /// - `tenant_id`: bound for the lifetime of this instance.
  ///   Injected into every query for multi-tenant isolation.
  /// - `config`: pool sizes and PRAGMA tuning.
  static Future<IronVaultDb> open({
    required String path,
    required List<int> encryptionKey,
    required String tenantId,
    required VaultConfig config,
  }) => RustLib.instance.api.crateApiVaultIronVaultDbOpen(
    path: path,
    encryptionKey: encryptionKey,
    tenantId: tenantId,
    config: config,
  );

  /// Execute a read query (SELECT).
  ///
  /// Uses the **read** connection pool (concurrent via WAL).
  /// Returns rows as a list of column-name → value maps.
  /// Parameters are bound positionally (`?1`, `?2`, ...).
  Future<List<Map<String, SqlValue>>> queryRaw({
    required String sql,
    required List<SqlValue> params,
  });

  /// Return a snapshot of database statistics.
  Future<VaultStats> stats();

  /// Reclaim disk space from deleted rows.
  ///
  /// Rewrites the entire database file. Can be very slow on large
  /// databases — prefer `incremental_vacuum` when available (Phase 12).
  Future<void> vacuum();
}
