// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `acquire_reader`, `acquire_writer`, `checkpoint_internal`, `ensure_open`, `execute_read_query`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<IronVaultDb>>
abstract class IronVaultDb implements RustOpaqueInterface {
  /// Trigger a WAL checkpoint.
  ///
  /// Returns the number of WAL pages and how many were successfully
  /// checkpointed. Call periodically (every ~15 min) and on app
  /// background to keep the WAL file from growing unbounded.
  Future<CheckpointResult> checkpoint({required CheckpointMode mode});

  /// Checkpoint WAL and mark the database as closed.
  ///
  /// After this call, all methods will return an error.
  /// Connection cleanup happens when the Dart GC drops this object.
  Future<void> close();

  /// Execute a write statement (INSERT, UPDATE, DELETE, DDL).
  ///
  /// Uses the **write** connection pool (serialized).
  /// Returns the number of rows affected.
  /// Parameters are bound positionally (`?1`, `?2`, ...).
  Future<BigInt> executeRaw({
    required String sql,
    required List<SqlValue> params,
  });

  /// Get the filesystem path of the database file.
  Future<String> getPath();

  /// Get the tenant ID bound to this database instance.
  Future<String> getTenantId();

  /// Run SQLite integrity check.
  ///
  /// Scans the entire database for corruption. Returns clean=true if
  /// no issues found. Can be slow on large databases — run sparingly.
  Future<IntegrityReport> integrityCheck();

  /// Open or create an encrypted database.
  ///
  /// - `path`: absolute filesystem path to the `.db` file.
  ///   Parent directory is created if it doesn't exist.
  /// - `encryption_key`: exactly 32 bytes (AES-256 key).
  ///   Derive with Argon2id; zero the Dart-side copy after this call.
  /// - `tenant_id`: bound for the lifetime of this instance.
  ///   Injected into every query for multi-tenant isolation.
  /// - `config`: pool sizes and PRAGMA tuning.
  static Future<IronVaultDb> open({
    required String path,
    required List<int> encryptionKey,
    required String tenantId,
    required VaultConfig config,
  }) => RustLib.instance.api.crateApiVaultIronVaultDbOpen(
    path: path,
    encryptionKey: encryptionKey,
    tenantId: tenantId,
    config: config,
  );

  /// Execute an aggregate query (COUNT, SUM, AVG, MIN, MAX).
  Future<Map<String, SqlValue>> queryAggregate({
    required QuerySpec spec,
    required List<AggExpr> expressions,
  });

  /// Count matching rows.
  Future<BigInt> queryCount({required QuerySpec spec});

  /// Soft-delete a row (sets `deleted_at` to current timestamp).
  ///
  /// Returns rows affected (0 if not found or already deleted).
  Future<BigInt> queryDelete({required String table, required String id});

  /// Soft-delete multiple rows in a single transaction. Returns total rows affected.
  Future<BigInt> queryDeleteBatch({
    required String table,
    required List<String> ids,
  });

  /// Check if any rows match.
  Future<bool> queryExists({required QuerySpec spec});

  /// Execute a query and return the first matching row (or None).
  Future<Map<String, SqlValue>?> queryFirst({required QuerySpec spec});

  /// Execute a query and return all matching rows.
  ///
  /// Tenant isolation and soft-delete guard are auto-injected.
  Future<List<Map<String, SqlValue>>> queryGet({required QuerySpec spec});

  /// Permanently delete a row (irreversible).
  ///
  /// Tenant isolation is enforced. Returns rows affected.
  Future<BigInt> queryHardDelete({required String table, required String id});

  /// Insert a row. Returns the generated or provided id.
  ///
  /// `tenant_id` is auto-injected. `id` is auto-generated (UUID) if not in data.
  /// `created_at` and `updated_at` are auto-set if not provided.
  Future<String> queryInsert({
    required String table,
    required Map<String, SqlValue> data,
  });

  /// Insert multiple rows in a single transaction. Returns list of ids.
  Future<List<String>> queryInsertBatch({
    required String table,
    required List<Map<String, SqlValue>> rows,
  });

  /// Execute a paginated query.
  ///
  /// `page` is 0-based. Returns a `Page` with items, total, and metadata.
  Future<Page> queryPaginate({
    required QuerySpec spec,
    required int page,
    required int pageSize,
  });

  /// Execute a read query (SELECT).
  ///
  /// Uses the **read** connection pool (concurrent via WAL).
  /// Returns rows as a list of column-name → value maps.
  /// Parameters are bound positionally (`?1`, `?2`, ...).
  Future<List<Map<String, SqlValue>>> queryRaw({
    required String sql,
    required List<SqlValue> params,
  });

  /// Update a row by id. Returns the number of rows affected (0 or 1).
  ///
  /// Tenant isolation and soft-delete guard are enforced.
  /// `updated_at` is auto-set if not in data.
  Future<BigInt> queryUpdate({
    required String table,
    required String id,
    required Map<String, SqlValue> data,
  });

  /// Update multiple rows in a single transaction. Returns total rows affected.
  Future<BigInt> queryUpdateBatch({
    required String table,
    required List<UpdateEntry> updates,
  });

  /// Upsert (insert or update on conflict).
  ///
  /// Returns the id of the inserted/updated row.
  Future<String> queryUpsert({
    required String table,
    required Map<String, SqlValue> data,
    required String conflictColumn,
  });

  /// Return a snapshot of database statistics.
  Future<VaultStats> stats();

  /// Reclaim disk space from deleted rows.
  ///
  /// Rewrites the entire database file. Can be very slow on large
  /// databases — prefer `incremental_vacuum` when available (Phase 12).
  Future<void> vacuum();
}
