// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `acquire_reader`, `acquire_writer`, `checkpoint_internal`, `ensure_open`, `execute_query_on_pool`, `execute_read_query`, `hash_results`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<IronVaultDb>>
abstract class IronVaultDb implements RustOpaqueInterface {
  /// Create a backup of the database.
  ///
  /// Optionally compresses (zstd) and encrypts (AES-256-GCM with
  /// HKDF-derived backup key). Returns the backup path, size, and
  /// BLAKE3 checksum for verification on restore.
  Future<BackupResult> backup({
    required String outputPath,
    required bool compress,
    required bool encrypt,
  });

  /// Build or open a Tantivy search index for a table.
  ///
  /// Call after creating the table (via migration or raw SQL).
  /// Fields define which columns are indexed and their weights.
  Future<void> buildSearchIndex({
    required String table,
    required List<SearchField> fields,
  });

  /// Trigger a WAL checkpoint.
  ///
  /// Returns the number of WAL pages and how many were successfully
  /// checkpointed. Call periodically (every ~15 min) and on app
  /// background to keep the WAL file from growing unbounded.
  Future<CheckpointResult> checkpoint({required CheckpointMode mode});

  /// Reset the actor ID to "system".
  Future<void> clearActor();

  /// Checkpoint WAL and mark the database as closed.
  ///
  /// After this call, all methods will return an error.
  /// Connection cleanup happens when the Dart GC drops this object.
  Future<void> close();

  /// Decrypt a ciphertext string produced by `encrypt_field`.
  ///
  /// Uses the same tenant-scoped key. Returns the original plaintext.
  /// Fails if the key is wrong or data has been tampered with.
  Future<String> decryptField({required String ciphertextJson});

  /// Derive an HKDF key for a specific purpose.
  ///
  /// Available purposes: "sqlcipher", "audit_hmac", "backup",
  /// or any custom string. Returns 32 bytes.
  Future<Uint8List> derivePurposeKey({required String purpose});

  /// Deserialize bytes back to Vec<f32>.
  static Float32List deserializeVector({required List<int> bytes}) => RustLib
      .instance
      .api
      .crateApiVaultIronVaultDbDeserializeVector(bytes: bytes);

  /// Stub when onnx feature is not enabled.
  Future<Float32List> embedText({required String text});

  /// Encrypt a plaintext string using AES-256-GCM.
  ///
  /// Uses a tenant-scoped key derived via HKDF from the master key.
  /// Each call produces different ciphertext (random 12-byte nonce).
  /// Returns JSON: `{"ct":"<base64>","nonce":"<base64>","kid":"v1"}`.
  Future<String> encryptField({required String plaintext});

  /// Execute a write statement (INSERT, UPDATE, DELETE, DDL).
  ///
  /// Uses the **write** connection pool (serialized).
  /// Returns the number of rows affected.
  /// Parameters are bound positionally (`?1`, `?2`, ...).
  Future<BigInt> executeRaw({
    required String sql,
    required List<SqlValue> params,
  });

  /// Export a table's data to CSV, JSON, or JSONL.
  ///
  /// Respects tenant isolation and soft-delete guard.
  Future<Uint8List> exportTable({
    required String table,
    required ExportFormat format,
    List<String>? columns,
  });

  /// Get the current actor ID.
  Future<String> getActor();

  /// Get audit history for a specific actor.
  Future<List<AuditEntry>> getActorHistory({
    required String actorId,
    PlatformInt64? from,
    PlatformInt64? to,
    required int limit,
  });

  /// Retrieve an embedding vector for a row.
  Future<Float32List> getEmbedding({required String table, required String id});

  /// Get audit history for a specific row.
  Future<List<AuditEntry>> getHistory({
    required String tableName,
    required String rowId,
    required int limit,
  });

  /// Get all applied migration records.
  Future<List<MigrationRecord>> getMigrations();

  /// Get the filesystem path of the database file.
  Future<String> getPath();

  /// Get audit history for an entire table.
  Future<List<AuditEntry>> getTableHistory({
    required String tableName,
    PlatformInt64? from,
    PlatformInt64? to,
    required int limit,
  });

  /// Get the tenant ID bound to this database instance.
  Future<String> getTenantId();

  /// Run SQLite integrity check.
  ///
  /// Scans the entire database for corruption. Returns clean=true if
  /// no issues found. Can be slow on large databases — run sparingly.
  Future<IntegrityReport> integrityCheck();

  /// Load an ONNX embedding model for on-device inference.
  ///
  /// Requires the `onnx` feature flag. Without it, returns an error.
  /// `dimension` is the expected output embedding size (e.g., 384).
  Future<void> loadEmbeddingModel({
    required String modelPath,
    required int dimension,
  });

  /// Run forward migrations.
  ///
  /// Applies all pending migrations (version > current) in version order.
  /// Each migration runs in its own transaction. If a migration fails,
  /// it is rolled back and an error is returned (previously-applied
  /// migrations remain intact).
  ///
  /// **Checksum protection:** if a previously-applied migration's SQL
  /// has been modified, returns `MigrationChecksumException`.
  Future<MigrationReport> migrate({required List<VaultMigration> migrations});

  /// Get the notification version for a table channel (for testing).
  Future<BigInt> notificationVersion({required String table});

  /// Open or create an encrypted database.
  ///
  /// - `path`: absolute filesystem path to the `.db` file.
  ///   Parent directory is created if it doesn't exist.
  /// - `encryption_key`: exactly 32 bytes (AES-256 key).
  ///   Derive with Argon2id; zero the Dart-side copy after this call.
  /// - `tenant_id`: bound for the lifetime of this instance.
  ///   Injected into every query for multi-tenant isolation.
  /// - `config`: pool sizes and PRAGMA tuning.
  static Future<IronVaultDb> open({
    required String path,
    required List<int> encryptionKey,
    required String tenantId,
    required VaultConfig config,
  }) => RustLib.instance.api.crateApiVaultIronVaultDbOpen(
    path: path,
    encryptionKey: encryptionKey,
    tenantId: tenantId,
    config: config,
  );

  /// Execute an aggregate query (COUNT, SUM, AVG, MIN, MAX).
  Future<Map<String, SqlValue>> queryAggregate({
    required QuerySpec spec,
    required List<AggExpr> expressions,
  });

  /// Count matching rows.
  Future<BigInt> queryCount({required QuerySpec spec});

  /// Soft-delete a row (sets `deleted_at` to current timestamp).
  ///
  /// Returns rows affected (0 if not found or already deleted).
  Future<BigInt> queryDelete({required String table, required String id});

  /// Soft-delete multiple rows in a single transaction. Returns total rows affected.
  Future<BigInt> queryDeleteBatch({
    required String table,
    required List<String> ids,
  });

  /// Check if any rows match.
  Future<bool> queryExists({required QuerySpec spec});

  /// Execute a query and return the first matching row (or None).
  Future<Map<String, SqlValue>?> queryFirst({required QuerySpec spec});

  /// Execute a query and return all matching rows.
  ///
  /// Tenant isolation and soft-delete guard are auto-injected.
  Future<List<Map<String, SqlValue>>> queryGet({required QuerySpec spec});

  /// Permanently delete a row (irreversible).
  ///
  /// Tenant isolation is enforced. Returns rows affected.
  Future<BigInt> queryHardDelete({required String table, required String id});

  /// Insert a row. Returns the generated or provided id.
  ///
  /// `tenant_id` is auto-injected. `id` is auto-generated (UUID) if not in data.
  /// `created_at` and `updated_at` are auto-set if not provided.
  Future<String> queryInsert({
    required String table,
    required Map<String, SqlValue> data,
  });

  /// Insert multiple rows in a single transaction. Returns list of ids.
  Future<List<String>> queryInsertBatch({
    required String table,
    required List<Map<String, SqlValue>> rows,
  });

  /// Execute a paginated query.
  ///
  /// `page` is 0-based. Returns a `Page` with items, total, and metadata.
  Future<Page> queryPaginate({
    required QuerySpec spec,
    required int page,
    required int pageSize,
  });

  /// Execute a read query (SELECT).
  ///
  /// Uses the **read** connection pool (concurrent via WAL).
  /// Returns rows as a list of column-name → value maps.
  /// Parameters are bound positionally (`?1`, `?2`, ...).
  Future<List<Map<String, SqlValue>>> queryRaw({
    required String sql,
    required List<SqlValue> params,
  });

  /// Update a row by id. Returns the number of rows affected (0 or 1).
  ///
  /// Tenant isolation and soft-delete guard are enforced.
  /// `updated_at` is auto-set if not in data.
  Future<BigInt> queryUpdate({
    required String table,
    required String id,
    required Map<String, SqlValue> data,
  });

  /// Update multiple rows in a single transaction. Returns total rows affected.
  Future<BigInt> queryUpdateBatch({
    required String table,
    required List<UpdateEntry> updates,
  });

  /// Upsert (insert or update on conflict).
  ///
  /// Returns the id of the inserted/updated row.
  Future<String> queryUpsert({
    required String table,
    required Map<String, SqlValue> data,
    required String conflictColumn,
  });

  /// Restore a backup to a target path.
  ///
  /// Does NOT require an open database — operates on files directly.
  /// Verifies checksum, decrypts, decompresses, runs integrity_check.
  Future<RestoreResult> restoreBackup({
    required String backupPath,
    required String targetPath,
    String? expectedChecksum,
  });

  /// Rollback to a target version.
  ///
  /// Rolls back all applied migrations with version > `target_version`,
  /// in reverse order. Each rollback executes the `down` SQL.
  ///
  /// Returns `MigrationNoRollbackException` if any migration lacks `down` SQL.
  /// The `migrations` list must include definitions for all versions to roll back.
  Future<MigrationReport> rollbackTo({
    required int targetVersion,
    required List<VaultMigration> migrations,
  });

  /// Search the index using Tantivy query syntax.
  ///
  /// Supports: simple words, "phrase search", field:value,
  /// boolean (AND OR NOT), fuzzy~N, wildcards, boost^N.
  /// Returns results ranked by relevance score.
  Future<List<SearchHit>> search({
    required String table,
    required String query,
    required int limit,
    required bool highlight,
  });

  /// Hybrid search combining FTS (Tantivy) and semantic (cosine) scores.
  ///
  /// 1. FTS returns candidates with BM25 scores
  /// 2. Cosine similarity computed for each candidate
  /// 3. Combined: score = fts_weight * bm25_norm + semantic_weight * cosine
  Future<List<HybridHit>> searchHybrid({
    required String table,
    required String query,
    required List<double> queryEmbedding,
    required double ftsWeight,
    required double semanticWeight,
    required int limit,
  });

  /// Index a single row in the search engine.
  ///
  /// `fields` maps column names to their text values.
  /// Call after insert/update to keep the index current.
  Future<void> searchIndexRow({
    required String table,
    required String id,
    required Map<String, String> fields,
  });

  /// Get statistics about a search index.
  Future<IndexStats> searchIndexStats({required String table});

  /// Remove a row from the search index.
  ///
  /// Call after soft-delete or hard-delete.
  Future<void> searchRemoveRow({required String table, required String id});

  /// Search for rows with similar embeddings using cosine similarity.
  ///
  /// Brute-force scan — efficient for <100k rows.
  /// Returns top-K results above the threshold, sorted by score.
  Future<List<SemanticHit>> searchSemantic({
    required String table,
    required List<double> queryEmbedding,
    required int topK,
    required double threshold,
  });

  /// Serialize a Vec<f32> to bytes for storage.
  static Uint8List serializeVector({required List<double> embedding}) => RustLib
      .instance
      .api
      .crateApiVaultIronVaultDbSerializeVector(embedding: embedding);

  /// Set the actor ID for audit logging.
  ///
  /// The actor is injected into every audit entry automatically.
  /// Call after authentication. Default is "system".
  Future<void> setActor({required String actorId});

  /// Return a snapshot of database statistics.
  Future<VaultStats> stats();

  /// Store an embedding vector for a row.
  ///
  /// The table must have an `embedding BLOB` column.
  /// The vector is serialized as little-endian f32 bytes.
  Future<void> storeEmbedding({
    required String table,
    required String id,
    required List<double> embedding,
  });

  /// Add a record to the sync outbox.
  Future<String> syncAddToOutbox({
    required String tableName,
    required String rowId,
    required String operation,
    required String payload,
    required VectorClock vectorClock,
  });

  /// Apply incoming sync records with conflict detection.
  Future<SyncApplyResult> syncApplyDelta({
    required SyncDelta delta,
    required ConflictResolution resolution,
  });

  /// Get unresolved sync conflicts.
  Future<List<SyncConflict>> syncGetConflicts();

  /// Get pending outbox records.
  Future<SyncDelta> syncGetDelta({
    required PlatformInt64 sinceSeq,
    required int limit,
  });

  /// Increment retry on a failed outbox record. Returns false if moved to dead-letter.
  Future<bool> syncIncrementRetry({
    required String recordId,
    required int maxAttempts,
    required String errorMessage,
  });

  /// Mark outbox records as synced.
  Future<int> syncMarkSynced({required List<String> recordIds});

  /// Resolve a sync conflict.
  Future<void> syncResolveConflict({
    required String conflictId,
    required String resolution,
  });

  /// Execute multiple operations in a single ACID transaction.
  ///
  /// All operations run inside `BEGIN IMMEDIATE ... COMMIT`.
  /// If any operation fails, the entire transaction is rolled back.
  /// Savepoints provide partial rollback within the transaction.
  ///
  /// Tenant isolation is enforced on all operations automatically.
  Future<TransactionResult> transaction({required List<Op> ops});

  /// Update a row with optimistic locking.
  ///
  /// Succeeds only if the row's `version` column matches `expected_version`.
  /// On success, `version` is incremented by 1 atomically.
  /// On mismatch (another writer updated first), returns
  /// `OptimisticLockException`.
  ///
  /// The table must have a `version INTEGER NOT NULL DEFAULT 1` column.
  Future<void> updateWithVersion({
    required String table,
    required String id,
    required PlatformInt64 expectedVersion,
    required Map<String, SqlValue> data,
  });

  /// Reclaim disk space from deleted rows.
  ///
  /// Rewrites the entire database file. Can be very slow on large
  /// databases — prefer `incremental_vacuum` when available (Phase 12).
  Future<void> vacuum();

  /// Verify integrity of audit log entries.
  ///
  /// Recomputes HMAC checksums and reports any tampered entries.
  Future<AuditIntegrityReport> verifyAuditIntegrity({
    PlatformInt64? from,
    PlatformInt64? to,
  });

  /// Verify a backup file without restoring.
  Future<BackupVerifyReport> verifyBackup({required String backupPath});

  /// Watch aggregate expressions — emits updated aggregates on table changes.
  Stream<Map<String, SqlValue>> watchAggregate({
    required QuerySpec spec,
    required List<AggExpr> expressions,
  });

  /// Watch a query — emits results whenever the table changes.
  ///
  /// Returns a Dart `Stream<List<Map<String, SqlValue>>>`.
  /// Initial result emitted immediately. Re-executes on every write
  /// to the table. Only emits if the result set actually changed
  /// (distinct emission via hash comparison).
  ///
  /// The stream stops when the Dart side cancels or the DB is closed.
  Stream<List<Map<String, SqlValue>>> watchQuery({required QuerySpec spec});

  /// Watch a single row — emits the row or None if soft-deleted.
  Stream<Map<String, SqlValue>?> watchRow({
    required String table,
    required String id,
  });

  /// Manually write an audit entry.
  ///
  /// For application-level events (login, export, etc.) that aren't
  /// automatic database writes. HMAC-signed with the audit key.
  Future<String> writeAudit({
    required String tableName,
    required String rowId,
    required String operation,
    String? beforeJson,
    String? afterJson,
    String? changedFields,
  });
}
